languageCode = "zh-Hant"
languageName = "æ­£é«”ä¸­æ–‡"
languageDirection = "ltr"
weight = 1

title = "DH's Blog"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "January 2, 2006"

  # mainSections = ["posts", "projects"]
  description = "ä¸»è¦åˆ†äº« Android é–‹ç™¼ä¸­ç¶“æ­·çš„å¤§å°äº‹ï¼Œå¶çˆ¾ä¹Ÿæœƒå¤¾é›œä¸€äº›èˆˆè¶£ä½¿ç„¶çš„æ±è¥¿ã€‚å¸Œæœ›æ¯å€‹èµ°é€²ä¾†çš„è®€è€…ï¼Œéƒ½èƒ½åœ¨é€™è£¡æ‰¾åˆ°è‡ªå·±éœ€è¦çš„æ±è¥¿ã€‚"

[params.author]
  name = "Daniel Huang"
  image = "img/author.jpg"
  headline = "An Android Developer from Taiwan! ğŸ‘¨â€ğŸ’»"
  bio = "ä¸€ä½ Android å·¥ç¨‹å¸«ï¼Œæ¯å¤©å°æ–¼å¦‚ä½•åœ¨èŒ«èŒ«æŠ€è¡“æµ·ä¸­å­˜æ´»æ„Ÿåˆ°æ†‚æ…®ã€‚æ¯æ¬¡å‹•ç­†éƒ½ä¸æ–·å‘Šè¨´è‡ªå·²ï¼Œç­†è¨˜ä¸æ˜¯ç‚ºäº†åˆ¥äººï¼Œæ˜¯ç‚ºäº†è‡ªå·±ã€‚"
  links = [
     { email = "mailto:danielhuang.work@gmail.com" },
     { github = "https://github.com/dh-46" },
     { linkedin = "https://linkedin.com/in/daniel-huang-2017" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
  ]
